=== delphic/zerog-webgl/shaders/GlslShaders.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="GlslShaders">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Shader" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Name" type="xs:string"/>
							<xs:element name="Type">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="x-shader/x-vertex"/>
										<xs:enumeration value="x-shader/x-fragment"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:element>
							<xs:element name="FileName" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== delphic/zerog-webgl/shaders/GlslShaders.xml
<?xml version="1.0"?>
<GlslShaders xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:schemaLocation="/ GlslShaders.xsd" >
	<Shader>
		<Name>vertex-shader-fs</Name>
    <Type>x-shader/x-fragment</Type>
		<FileName>vertex-shader-fs.glsl</FileName>
	</Shader>
  <Shader>
    <Name>vertex-shader-vs</Name>
    <Type>x-shader/x-vertex</Type>
    <FileName>vertex-shader-vs.glsl</FileName>
  </Shader>
  <Shader>
    <Name>pixel-shader-fs</Name>
    <Type>x-shader/x-fragment</Type>
    <FileName>pixel-shader-fs.glsl</FileName>
  </Shader>
  <Shader>
    <Name>pixel-shader-vs</Name>
    <Type>x-shader/x-vertex</Type>
    <FileName>pixel-shader-vs.glsl</FileName>
  </Shader>
</GlslShaders>
